spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.67.142.108:13306/KAKAODB?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: kakao
    password: Kakao123!@
  jpa:
    hibernate:
      ddl-auto: update  # 개발 환경에서는 update, 운영 환경에서는 validate 또는 none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialoect: org.hibernate.dialect.MySQL8Dialect
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 3MB
  web:
    resources:
      static-locations: classpath:/static/
server:
  port: 8446
  tomcat:
    additional-tld-skip-patterns: .jar
logging:
  level:
    com:
      example:
        kakaochat: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
mybatis:
   mapper-locations: classpath*:mybatis/mapper/*.xml
   config-location: classpath:mybatis/mybatis-config.xml